/// <reference no-default-lib="true"/>
/// <reference path="libraries/drawing.d.ts" />
/// <reference path="functions/env.d.ts" />
/// <reference path="functions/fs.d.ts" />
/// <reference path="functions/hooking.d.ts" />
/// <reference path="functions/input.d.ts" />
/// <reference path="functions/misc.d.ts" />
/// <reference path="functions/reflection.d.ts" />
/// <reference path="functions/script.d.ts" />
